dist: bionic
language: python
os: linux
sudo: required
if: branch = master

python:
- "3.8"

#TODO: set redhat-operator-ecosystem/operator-test-playbooks
env:
- DISTRO_TYPE=upstream

# in travis configuration
# ANSIBLE_BASE_ARGS="-i localhost, local.yml -e ansible_connection=local -e run_upstream=true -e run_remove_catalog_repo=false"
# ANSIBLE_EXTRA_ARGS=""
# ANSIBLE_PULL_REPO=https://github.com/redhat-operator-ecosystem/operator-test-playbooks
# ANSIBLE_PULL_BRANCH='upstream-community'

services:
  - docker

install:
# check-pr needs to be sourced so it can pass release early.
- source scripts/ci/check-release $DISTRO_TYPE

before_script:
#original
  - pip install ansible jmespath

jobs:
  include:

  - stage: Traffic light for all tests - Go/Stop
    if: type = pull_request
    name: Run tests only on operator modification, otherwise red and stop all tests.
    script:
    - scripts/ci/PR-traffic-light
    before_script: skip
    install: skip
    services: skip
    before_install: skip

  - stage: Bundle Test Pipeline
    if: type = pull_request
    name: Bundle Test Pipeline
    script:
    - scripts/ci/run-ansible-tests
    install: skip
    before_install: skip

  - name: Test if release by bundle pipeline is possible from production registry
    if: type = pull_request
    script:
    - scripts/ci/run-release -t prod
    install: skip
    before_install: skip

  - stage: operatorhubio prod deploy
    if: type = push
    name: Trigger PROD deploy of operatorhub.io
    script: scripts/ci/trigger-operatorhubio-ci.sh
    before_install: skip
    before_script: skip

  - stage: Release pipeline
    if: type = push
    name: Trigger release on community-operator-catalog
    script: scripts/ci/trigger-community-op-catalog-ci-release.sh
    services: skip
    before_script: skip
    before_install: skip

  - stage: Release pipeline Push to Quay
    if: type = push
    name: Push to Quay
    script: scripts/ci/push-to-quay
    before_install: skip
